name: flutter_shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  connectivity_plus: ^2.3.0
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  badges: ^3.1.1
  fluttertoast: ^8.2.5
  dio: ^5.4.3+1
  freezed_annotation: ^2.0.0
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.0
  freezed: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - images/empty_cart.png
